# Generated by Django 5.1.5 on 2025-02-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='pagemanager',
            options={'verbose_name': 'Менеджер страницы', 'verbose_name_plural': 'Менеджеры страницы'},
        ),
        migrations.AlterUniqueTogether(
            name='pagemanager',
            unique_together=set(),
        ),
    ]
